### ISSUE TITLE
Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by lumpysimon** [avillegasn/nelio-testimonial-block#1]
I've installed this plugin after reading your tutorial with the aim of adapting it to write my own blocks.

However, the block is not showing in the list of available blocks. The following error is showing in the console:

```
Uncaught TypeError: Cannot read property 'children' of undefined
    at block.js?ver=1521743283:3
    at block.js?ver=1521743283:172
```

Line 3 is this one:

```
var children = blocks.source.children;
```

Do you know what needs changing to get it to work?

I'm using Gutenberg v2.4.0.

**Comment by lumpysimon** [comment]
I've discovered that commenting out line 3 does the trick, but I'm not sure if that will have any unintended consequences?

**Comment by avillegasn** [comment]
You're right. There were unused variables. I've removed them in the last commit. Now it works fine with v2.4.0.

**Comment by lumpysimon** [comment]
Thank you, all good now
