### ISSUE TITLE
Console log error

### ISSUE THREAD

**Issue by gonzalesc** [avillegasn/nelio-testimonial-block#2]
It shows a error:

react-dom.min.82e21c65.js:110 :  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

UPDATE
---------
The error is here : blocks.RichText

**Comment by andreawo** [comment]
Some components have been moved and I had to make changes in block.js:

var RichText = wp.editor.RichText; 
var MediaUpload = wp.editor.MediaUpload;
var IconButton = components.IconButton;

blocks.RichText -> RichText
blocks.MediaUpload -> MediaUpload
components.Button -> IconButton

The render function of MediaUpload also didn't work and I have changed it from:

el(MediaUpload, {
  onSelect: onSelectImage,
  type: 'image',
  value: attributes.mediaID,
  render: function (obj) {
    return el(components.Button, {
      className: attributes.mediaID ? 'image-button' : 'button button-large',
      onClick: obj.open
    },
            !attributes.mediaID ? i18n.__('Upload Image') : el('img', {src: attributes.mediaURL})
            );
  }
})

to:

el(MediaUpload, {
  onSelect: onSelectImage,
  type: 'image',
  value: attributes.mediaID,
  render: function render(obj) {
    return el(IconButton, {
      className: attributes.mediaID ? 'image-button' : 'button button-large',
      onClick: obj.open
    },
            !attributes.mediaID ? i18n.__('Upload Image') : el('img', {src: attributes.mediaURL})
            );
  }
})

Now it works fine!
Nelio developers, thank you so much for the gutenberg code example!!!

Andrea

[block.zip](https://github.com/avillegasn/nelio-testimonial-block/files/2290697/block.zip)

**Comment by avillegasn** [comment]
Thanks @andreawo. I've applied the changes 👍
